# Travis CI build file
language: java
jdk:
  - oraclejdk8

git:
  depth: 3

install:
  - pushd .. 
  - git clone -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --depth 3 --recursive https://github.com/esoco/sdack
  - cd sdack
  - git submodule foreach git checkout ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - popd

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
